-- Reverse initial schema
DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS alarm_configs CASCADE;
DROP TABLE IF EXISTS firewall_rules CASCADE;
DROP TABLE IF EXISTS faa_registry CASCADE;
DROP TABLE IF EXISTS chat_messages CASCADE;
DROP TABLE IF EXISTS commands CASCADE;
DROP TABLE IF EXISTS webhooks CASCADE;
DROP TABLE IF EXISTS alert_events CASCADE;
DROP TABLE IF EXISTS alert_rules CASCADE;
DROP TABLE IF EXISTS geofences CASCADE;
DROP TABLE IF EXISTS target_positions CASCADE;
DROP TABLE IF EXISTS targets CASCADE;
DROP TABLE IF EXISTS inventory_devices CASCADE;
DROP TABLE IF EXISTS drone_detections CASCADE;
DROP TABLE IF EXISTS drones CASCADE;
DROP TABLE IF EXISTS node_positions CASCADE;
DROP TABLE IF EXISTS nodes CASCADE;
DROP TABLE IF EXISTS app_config CASCADE;
DROP TABLE IF EXISTS password_resets CASCADE;
DROP TABLE IF EXISTS invitations CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS sites CASCADE;

DROP TYPE IF EXISTS node_role;
DROP TYPE IF EXISTS webhook_method;
DROP TYPE IF EXISTS geofence_action;
DROP TYPE IF EXISTS command_status;
DROP TYPE IF EXISTS alert_severity;
DROP TYPE IF EXISTS drone_status;
DROP TYPE IF EXISTS user_role;

DROP EXTENSION IF EXISTS "uuid-ossp";
