-- Phase 4: Target tracking enrichment
ALTER TABLE targets ADD COLUMN IF NOT EXISTS url TEXT;
ALTER TABLE targets ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';
ALTER TABLE targets ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE targets ADD COLUMN IF NOT EXISTS first_node_id TEXT;
ALTER TABLE targets ADD COLUMN IF NOT EXISTS tracking_confidence DOUBLE PRECISION;
ALTER TABLE targets ADD COLUMN IF NOT EXISTS tracking_uncertainty DOUBLE PRECISION;
ALTER TABLE targets ADD COLUMN IF NOT EXISTS triangulation_method TEXT;
ALTER TABLE targets ADD COLUMN IF NOT EXISTS notes TEXT;
