ALTER TABLE inventory_devices ADD COLUMN IF NOT EXISTS hits INTEGER DEFAULT 0;
ALTER TABLE inventory_devices ADD COLUMN IF NOT EXISTS rssi_min INTEGER;
ALTER TABLE inventory_devices ADD COLUMN IF NOT EXISTS rssi_max INTEGER;
ALTER TABLE inventory_devices ADD COLUMN IF NOT EXISTS rssi_avg DOUBLE PRECISION;
ALTER TABLE inventory_devices ADD COLUMN IF NOT EXISTS last_node_id UUID REFERENCES nodes(id) ON DELETE SET NULL;
ALTER TABLE inventory_devices ADD COLUMN IF NOT EXISTS last_latitude DOUBLE PRECISION;
ALTER TABLE inventory_devices ADD COLUMN IF NOT EXISTS last_longitude DOUBLE PRECISION;
