-- Command enrichment: structured fields + ACK tracking
ALTER TABLE commands ADD COLUMN IF NOT EXISTS target TEXT;
ALTER TABLE commands ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE commands ADD COLUMN IF NOT EXISTS params TEXT[];
ALTER TABLE commands ADD COLUMN IF NOT EXISTS line TEXT;
ALTER TABLE commands ADD COLUMN IF NOT EXISTS finished_at TIMESTAMPTZ;
ALTER TABLE commands ADD COLUMN IF NOT EXISTS ack_kind TEXT;
ALTER TABLE commands ADD COLUMN IF NOT EXISTS ack_status TEXT;
ALTER TABLE commands ADD COLUMN IF NOT EXISTS ack_node TEXT;
ALTER TABLE commands ADD COLUMN IF NOT EXISTS result_text TEXT;
ALTER TABLE commands ADD COLUMN IF NOT EXISTS error_text TEXT;
