package fleetsec

import (
	"context"
	"errors"
	"fmt"

	pb "github.com/karamble/diginode-cc/internal/meshpb"
)

// Identity captures the active control-center identity as displayed in
// the Fleet Security tab's Identity card. Fingerprint is always
// populated; Label is populated when the pubkey matches a registered
// IdentityRecord, otherwise empty (which the UI shows as "<unknown>").
type Identity struct {
	PublicKey   []byte         `json:"-"`
	Fingerprint string         `json:"fingerprint"`
	Label       string         `json:"label,omitempty"`
	Role        IdentityRole   `json:"role,omitempty"`
	Source      IdentitySource `json:"source,omitempty"`
}

// GetIdentity returns the active control-center identity by querying
// the local Heltec's SecurityConfig and joining against fleet_identities.
//
// Side effect: if the local Heltec's pubkey isn't yet registered, this
// auto-registers it as IdentityRoleOperator with source AutoGenerated.
// Rationale: a fresh diginode-cc installation that connects to a Heltec
// with an existing keypair shouldn't require operator action before
// trust display works -- the auto-entry can be relabelled later.
func (s *Service) GetIdentity(ctx context.Context) (*Identity, error) {
	defer s.adminLockLocal()()

	reply, err := s.runLocalAdmin(ctx, AdminGetConfig(pb.AdminMessage_SECURITY_CONFIG), "local-get-security")
	if err != nil {
		return nil, fmt.Errorf("read local security: %w", err)
	}
	sec, err := extractSecurityConfig(reply)
	if err != nil {
		return nil, err
	}
	pub := sec.GetPublicKey()
	if err := ValidateX25519PublicKey(pub); err != nil {
		return nil, fmt.Errorf("local Heltec pubkey: %w", err)
	}

	id := &Identity{
		PublicKey:   pub,
		Fingerprint: Fingerprint(pub),
	}

	rec, err := s.store.GetIdentityByFingerprint(ctx, id.Fingerprint)
	if errors.Is(err, ErrNotFound) {
		// Auto-register with a placeholder label so trust diffs work
		// from the start. Operator can rename via the registry modal.
		newRec := IdentityRecord{
			Label:       fmt.Sprintf("local-heltec-%s", id.Fingerprint[:5]),
			PublicKey:   pub,
			Fingerprint: id.Fingerprint,
			Role:        IdentityRolePrimary,
			Source:      IdentitySourceAutoGenerated,
		}
		if _, regErr := s.store.InsertIdentity(ctx, newRec); regErr != nil {
			return nil, fmt.Errorf("auto-register local pubkey: %w", regErr)
		}
		id.Label = newRec.Label
		id.Role = newRec.Role
		id.Source = newRec.Source
		s.auditFleet(ctx, "", "auto_register_local", "identity", id.Fingerprint, map[string]any{
			"label": newRec.Label,
		})
		return id, nil
	}
	if err != nil {
		return nil, err
	}

	id.Label = rec.Label
	id.Role = rec.Role
	id.Source = rec.Source
	return id, nil
}

// ImportIdentity pushes an operator-supplied keypair to the local
// Heltec and registers the pubkey in the identity registry as the new
// primary. The privkey bytes are zeroed on the way out.
//
// Use cases:
//   - First-time setup: operator generates a keypair offline and
//     deterministically provisions the control-center Heltec.
//   - Disaster recovery: operator flashes a fresh Heltec with a
//     previously-escrowed keypair to resume admin without touching
//     deployed nodes.
//
// userID is the JWT-context user driving the request; threaded through
// for the audit log.
//
// Caveat: this changes the local Heltec's identity. Phone clients
// bonded to the old pubkey will need to re-pair. Other mesh nodes'
// NodeDB caches will be stale until they hear a fresh NodeInfo.
func (s *Service) ImportIdentity(ctx context.Context, userID, label string, priv, pub []byte) (*IdentityRecord, error) {
	if err := ValidateX25519PrivateKey(priv); err != nil {
		return nil, fmt.Errorf("priv: %w", err)
	}
	if err := ValidateX25519PublicKey(pub); err != nil {
		return nil, fmt.Errorf("pub: %w", err)
	}

	// Verify the priv/pub pair matches -- catches paste errors before
	// the keys hit the Heltec.
	derived, err := DerivePubkey(priv)
	if err != nil {
		return nil, fmt.Errorf("derive pubkey for verification: %w", err)
	}
	if !bytesEqual(derived, pub) {
		return nil, errors.New("supplied private key does not match supplied public key")
	}

	defer s.adminLockLocal()()

	// Hold the privkey in a SecretBytes so the deferred Clear() runs
	// no matter how we exit.
	secret := NewSecret(append([]byte(nil), priv...))
	defer secret.Clear()

	msg := AdminSetSecurity(SecurityConfigUpdate{
		PublicKey:  pub,
		PrivateKey: secret.Bytes(),
	})
	if _, err := s.runLocalAdmin(ctx, msg, "local-set-security-import"); err != nil {
		return nil, fmt.Errorf("push to local Heltec: %w", err)
	}

	rec := IdentityRecord{
		Label:       label,
		PublicKey:   pub,
		Fingerprint: Fingerprint(pub),
		Role:        IdentityRolePrimary,
		Source:      IdentitySourceImported,
	}
	id, err := s.store.InsertIdentity(ctx, rec)
	if err != nil {
		return nil, fmt.Errorf("register identity: %w", err)
	}
	rec.ID = id

	s.auditFleet(ctx, userID, "import_identity", "identity", rec.Fingerprint, map[string]any{
		"label": label,
		// priv intentionally omitted -- redactSecrets would catch it
		// even if a future caller leaked it here.
	})
	return &rec, nil
}

// ListIdentities returns the registry, ordered by status (active first,
// then revoked). Revoked entries are kept so audit_log entries stay
// resolvable to a label.
func (s *Service) ListIdentities(ctx context.Context) ([]IdentityRecord, error) {
	return s.store.ListIdentities(ctx)
}

// RegisterIdentity adds an externally-generated pubkey to the registry
// (no Heltec push). Used for "Add operator" / "Add rescue key" flows
// where the privkey lives outside diginode-cc and only the pubkey is
// shared.
func (s *Service) RegisterIdentity(ctx context.Context, userID, label string, pub []byte, role IdentityRole) (*IdentityRecord, error) {
	if err := ValidateX25519PublicKey(pub); err != nil {
		return nil, err
	}
	switch role {
	case IdentityRolePrimary, IdentityRoleRescue, IdentityRoleOperator:
		// ok
	default:
		return nil, fmt.Errorf("invalid role %q for new identity", role)
	}
	rec := IdentityRecord{
		Label:       label,
		PublicKey:   pub,
		Fingerprint: Fingerprint(pub),
		Role:        role,
		Source:      IdentitySourceImported,
	}
	id, err := s.store.InsertIdentity(ctx, rec)
	if err != nil {
		return nil, fmt.Errorf("register identity: %w", err)
	}
	rec.ID = id

	s.auditFleet(ctx, userID, "register_identity", "identity", rec.Fingerprint, map[string]any{
		"label": label,
		"role":  role,
	})
	return &rec, nil
}

// RevokeIdentity marks an entry revoked. The pubkey row stays so audit
// references stay resolvable. Does NOT push admin_key changes to the
// fleet -- the operator is expected to follow up by removing the pubkey
// from each node's admin_key (via SetAdminKeys) or via a future
// "Reconcile drift" action.
func (s *Service) RevokeIdentity(ctx context.Context, userID, fingerprint, reason string) error {
	if err := s.store.RevokeIdentity(ctx, fingerprint, reason); err != nil {
		return err
	}
	s.auditFleet(ctx, userID, "revoke_identity", "identity", fingerprint, map[string]any{
		"reason": reason,
	})
	return nil
}

// ExportPubkey returns the active control-center identity's pubkey
// (base64-encoded for clipboard friendliness) plus its fingerprint.
// Safe operation -- no special auth needed beyond the Fleet Security
// tab's read role.
func (s *Service) ExportPubkey(ctx context.Context) (b64, fingerprint string, err error) {
	id, err := s.GetIdentity(ctx)
	if err != nil {
		return "", "", err
	}
	return EncodePubkeyB64(id.PublicKey), id.Fingerprint, nil
}

// bytesEqual is a length-prefixed equality so we don't bring in a
// dependency just for one call site.
func bytesEqual(a, b []byte) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
