package fleetsec

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/karamble/diginode-cc/internal/database"
)

// Store wraps the database queries for fleetsec rows. Mirrors the pattern
// used by audit.Service and other internal services -- thin layer on top
// of database.DB.Pool that hides the raw SQL from the service core.
type Store struct {
	db *database.DB
}

// NewStore constructs a Store over the provided database handle.
func NewStore(db *database.DB) *Store {
	return &Store{db: db}
}

// ErrNotFound is returned when a single-row lookup matches no rows.
var ErrNotFound = errors.New("fleetsec: not found")

// --- Identity registry ---

func (s *Store) ListIdentities(ctx context.Context) ([]IdentityRecord, error) {
	rows, err := s.db.Pool.Query(ctx, `
		SELECT id::text, label, public_key, fingerprint, role, source,
		       created_at, revoked_at, COALESCE(revoked_reason, ''),
		       COALESCE(notes, '')
		  FROM fleet_identities
		 ORDER BY (revoked_at IS NOT NULL), created_at DESC`)
	if err != nil {
		return nil, fmt.Errorf("list identities: %w", err)
	}
	defer rows.Close()

	var out []IdentityRecord
	for rows.Next() {
		var r IdentityRecord
		if err := rows.Scan(&r.ID, &r.Label, &r.PublicKey, &r.Fingerprint,
			&r.Role, &r.Source, &r.CreatedAt, &r.RevokedAt,
			&r.RevokedReason, &r.Notes); err != nil {
			return nil, fmt.Errorf("scan identity: %w", err)
		}
		out = append(out, r)
	}
	return out, rows.Err()
}

func (s *Store) GetIdentityByFingerprint(ctx context.Context, fp string) (*IdentityRecord, error) {
	var r IdentityRecord
	err := s.db.Pool.QueryRow(ctx, `
		SELECT id::text, label, public_key, fingerprint, role, source,
		       created_at, revoked_at, COALESCE(revoked_reason, ''),
		       COALESCE(notes, '')
		  FROM fleet_identities
		 WHERE fingerprint = $1`, fp).
		Scan(&r.ID, &r.Label, &r.PublicKey, &r.Fingerprint, &r.Role, &r.Source,
			&r.CreatedAt, &r.RevokedAt, &r.RevokedReason, &r.Notes)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("get identity by fingerprint: %w", err)
	}
	return &r, nil
}

// InsertIdentity creates a new entry. Caller is responsible for filling in
// Label, PublicKey, Fingerprint, Role, Source -- ID is generated by the DB.
func (s *Store) InsertIdentity(ctx context.Context, r IdentityRecord) (string, error) {
	var id string
	err := s.db.Pool.QueryRow(ctx, `
		INSERT INTO fleet_identities (label, public_key, fingerprint, role, source, notes)
		VALUES ($1, $2, $3, $4, $5, NULLIF($6, ''))
		RETURNING id::text`,
		r.Label, r.PublicKey, r.Fingerprint, r.Role, r.Source, r.Notes).
		Scan(&id)
	if err != nil {
		return "", fmt.Errorf("insert identity: %w", err)
	}
	return id, nil
}

// RevokeIdentity marks the identity revoked in-place. The pubkey row
// stays so that audit-log entries referencing this fingerprint remain
// resolvable to a label (just shows "<label> (revoked)" in UI).
func (s *Store) RevokeIdentity(ctx context.Context, fp, reason string) error {
	tag, err := s.db.Pool.Exec(ctx, `
		UPDATE fleet_identities
		   SET role = 'revoked',
		       revoked_at = NOW(),
		       revoked_reason = NULLIF($2, '')
		 WHERE fingerprint = $1`, fp, reason)
	if err != nil {
		return fmt.Errorf("revoke identity: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// --- Trust roster ---

// ListNodeTrust returns one row per known node, joined with the trust
// snapshot. Nodes without a trust row appear with default zero values
// and DriftStatus=unknown, so the UI naturally shows "unknown / not yet
// verified" for newly-discovered nodes.
func (s *Store) ListNodeTrust(ctx context.Context) ([]NodeTrustRecord, error) {
	rows, err := s.db.Pool.Query(ctx, `
		SELECT n.node_num,
		       COALESCE(n.node_id, ''),
		       COALESCE(n.long_name, ''),
		       COALESCE(n.short_name, ''),
		       COALESCE(n.sensor_short_id, ''),
		       n.last_heard,
		       COALESCE(n.is_online, false),
		       COALESCE(t.admin_key_fps, '[]'::jsonb),
		       COALESCE(t.is_managed, false),
		       t.last_verified_at,
		       COALESCE(t.last_verify_method, ''),
		       t.last_drift_check_at,
		       COALESCE(t.drift_status, 'unknown'),
		       COALESCE(t.current_psk_fp, ''),
		       COALESCE(t.notes, '')
		  FROM nodes n
		  LEFT JOIN fleet_node_trust t ON t.node_num = n.node_num
		 ORDER BY n.last_heard DESC NULLS LAST, n.node_num`)
	if err != nil {
		return nil, fmt.Errorf("list node trust: %w", err)
	}
	defer rows.Close()

	var out []NodeTrustRecord
	for rows.Next() {
		var r NodeTrustRecord
		var nodeNum int64
		var fpsJSON []byte
		if err := rows.Scan(&nodeNum, &r.NodeID, &r.LongName, &r.ShortName,
			&r.SensorShortID, &r.LastHeard, &r.IsOnline, &fpsJSON,
			&r.IsManaged, &r.LastVerifiedAt, &r.LastVerifyMethod,
			&r.LastDriftCheckAt, &r.DriftStatus, &r.CurrentPSKFP, &r.Notes); err != nil {
			return nil, fmt.Errorf("scan node trust: %w", err)
		}
		r.NodeNum = uint32(nodeNum)
		if err := json.Unmarshal(fpsJSON, &r.AdminKeyFPs); err != nil {
			return nil, fmt.Errorf("decode admin_key_fps for node %d: %w", nodeNum, err)
		}
		out = append(out, r)
	}
	return out, rows.Err()
}

// GetNodeTrust returns a single row, joined the same way as ListNodeTrust.
// Returns ErrNotFound if the node doesn't exist in the nodes table.
func (s *Store) GetNodeTrust(ctx context.Context, nodeNum uint32) (*NodeTrustRecord, error) {
	var r NodeTrustRecord
	var nn int64
	var fpsJSON []byte
	err := s.db.Pool.QueryRow(ctx, `
		SELECT n.node_num,
		       COALESCE(n.node_id, ''),
		       COALESCE(n.long_name, ''),
		       COALESCE(n.short_name, ''),
		       COALESCE(n.sensor_short_id, ''),
		       n.last_heard,
		       COALESCE(n.is_online, false),
		       COALESCE(t.admin_key_fps, '[]'::jsonb),
		       COALESCE(t.is_managed, false),
		       t.last_verified_at,
		       COALESCE(t.last_verify_method, ''),
		       t.last_drift_check_at,
		       COALESCE(t.drift_status, 'unknown'),
		       COALESCE(t.current_psk_fp, ''),
		       COALESCE(t.notes, '')
		  FROM nodes n
		  LEFT JOIN fleet_node_trust t ON t.node_num = n.node_num
		 WHERE n.node_num = $1`, int64(nodeNum)).
		Scan(&nn, &r.NodeID, &r.LongName, &r.ShortName, &r.SensorShortID,
			&r.LastHeard, &r.IsOnline, &fpsJSON, &r.IsManaged,
			&r.LastVerifiedAt, &r.LastVerifyMethod, &r.LastDriftCheckAt,
			&r.DriftStatus, &r.CurrentPSKFP, &r.Notes)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("get node trust: %w", err)
	}
	r.NodeNum = uint32(nn)
	if err := json.Unmarshal(fpsJSON, &r.AdminKeyFPs); err != nil {
		return nil, fmt.Errorf("decode admin_key_fps: %w", err)
	}
	return &r, nil
}

// UpsertNodeTrust writes the trust snapshot for a node, creating the row
// if it doesn't exist. Used after a successful get_config(SECURITY) reply.
func (s *Store) UpsertNodeTrust(ctx context.Context, r NodeTrustRecord) error {
	fpsJSON, err := json.Marshal(r.AdminKeyFPs)
	if err != nil {
		return fmt.Errorf("encode admin_key_fps: %w", err)
	}
	if r.AdminKeyFPs == nil {
		fpsJSON = []byte(`[]`)
	}
	_, err = s.db.Pool.Exec(ctx, `
		INSERT INTO fleet_node_trust (
			node_num, admin_key_fps, is_managed,
			last_verified_at, last_verify_method,
			last_drift_check_at, drift_status, notes
		) VALUES ($1, $2, $3, $4, NULLIF($5, ''), $6, $7, NULLIF($8, ''))
		ON CONFLICT (node_num) DO UPDATE SET
			admin_key_fps       = EXCLUDED.admin_key_fps,
			is_managed          = EXCLUDED.is_managed,
			last_verified_at    = COALESCE(EXCLUDED.last_verified_at, fleet_node_trust.last_verified_at),
			last_verify_method  = COALESCE(EXCLUDED.last_verify_method, fleet_node_trust.last_verify_method),
			last_drift_check_at = COALESCE(EXCLUDED.last_drift_check_at, fleet_node_trust.last_drift_check_at),
			drift_status        = EXCLUDED.drift_status,
			notes               = COALESCE(EXCLUDED.notes, fleet_node_trust.notes)`,
		int64(r.NodeNum), fpsJSON, r.IsManaged,
		r.LastVerifiedAt, string(r.LastVerifyMethod),
		r.LastDriftCheckAt, string(r.DriftStatus), r.Notes)
	if err != nil {
		return fmt.Errorf("upsert node trust: %w", err)
	}
	return nil
}

// --- Channels ---

func (s *Store) ListChannels(ctx context.Context) ([]ChannelRecord, error) {
	rows, err := s.db.Pool.Query(ctx, `
		SELECT channel_index, name, role,
		       COALESCE(psk_fingerprint, ''), COALESCE(psk_length, 0),
		       last_rotated_at, COALESCE(last_rotated_by::text, ''),
		       COALESCE(last_rotation_id::text, '')
		  FROM fleet_channels
		 ORDER BY channel_index`)
	if err != nil {
		return nil, fmt.Errorf("list channels: %w", err)
	}
	defer rows.Close()

	var out []ChannelRecord
	for rows.Next() {
		var r ChannelRecord
		if err := rows.Scan(&r.Index, &r.Name, &r.Role, &r.PSKFingerprint,
			&r.PSKLength, &r.LastRotatedAt, &r.LastRotatedBy,
			&r.LastRotationID); err != nil {
			return nil, fmt.Errorf("scan channel: %w", err)
		}
		out = append(out, r)
	}
	return out, rows.Err()
}

// UpsertChannel writes a snapshot for one channel index.
func (s *Store) UpsertChannel(ctx context.Context, r ChannelRecord) error {
	_, err := s.db.Pool.Exec(ctx, `
		INSERT INTO fleet_channels (
			channel_index, name, role, psk_fingerprint, psk_length,
			last_rotated_at, last_rotated_by, last_rotation_id
		) VALUES ($1, $2, $3, NULLIF($4, ''), NULLIF($5, 0)::int,
		          $6, NULLIF($7, '')::uuid, NULLIF($8, '')::uuid)
		ON CONFLICT (channel_index) DO UPDATE SET
			name             = EXCLUDED.name,
			role             = EXCLUDED.role,
			psk_fingerprint  = COALESCE(EXCLUDED.psk_fingerprint, fleet_channels.psk_fingerprint),
			psk_length       = COALESCE(EXCLUDED.psk_length, fleet_channels.psk_length),
			last_rotated_at  = COALESCE(EXCLUDED.last_rotated_at, fleet_channels.last_rotated_at),
			last_rotated_by  = COALESCE(EXCLUDED.last_rotated_by, fleet_channels.last_rotated_by),
			last_rotation_id = COALESCE(EXCLUDED.last_rotation_id, fleet_channels.last_rotation_id)`,
		r.Index, r.Name, string(r.Role), r.PSKFingerprint, r.PSKLength,
		r.LastRotatedAt, r.LastRotatedBy, r.LastRotationID)
	if err != nil {
		return fmt.Errorf("upsert channel: %w", err)
	}
	return nil
}

// --- Rotations ---

// InsertRotation creates a new rotation row and returns its UUID. Targets
// are typically all in 'pending' status at insert time; UpdateRotation
// transitions them as the orchestrator processes them.
//
// rawPSK is stored on fleet_rotations.new_psk so RetryRotation can resume
// the same rotation without the operator having to re-supply 16 random
// bytes they never saw. ClearRotationPSK nulls the column once every
// target has reached acked. Pass nil for non-PSK rotations.
func (s *Store) InsertRotation(ctx context.Context, r RotationRecord, rawPSK []byte) (string, error) {
	targets, err := json.Marshal(r.Targets)
	if err != nil {
		return "", fmt.Errorf("encode targets: %w", err)
	}
	var id string
	err = s.db.Pool.QueryRow(ctx, `
		INSERT INTO fleet_rotations (kind, channel_index, started_by, targets, new_psk_fp, notes, new_psk)
		VALUES ($1, $2, NULLIF($3, '')::uuid, $4, NULLIF($5, ''), NULLIF($6, ''), $7)
		RETURNING id::text`,
		string(r.Kind), r.ChannelIndex, r.StartedBy, targets, r.NewPSKFP, r.Notes, rawPSK).
		Scan(&id)
	if err != nil {
		return "", fmt.Errorf("insert rotation: %w", err)
	}
	return id, nil
}

// GetRotationPSK fetches the persisted raw PSK for an in-flight rotation.
// Returns (nil, nil) when the column is NULL -- either the rotation has
// fully completed (PSK cleared by ClearRotationPSK) or the rotation
// pre-dates migration 000026. Caller treats nil as "operator must supply".
func (s *Store) GetRotationPSK(ctx context.Context, id string) ([]byte, error) {
	var psk []byte
	err := s.db.Pool.QueryRow(ctx,
		`SELECT new_psk FROM fleet_rotations WHERE id = $1`, id).Scan(&psk)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("get rotation psk: %w", err)
	}
	return psk, nil
}

// MarkTrustVerifiedNow refreshes only the verification timestamps on a
// trust row, without re-reading SecurityConfig. Called when a successful
// admin operation (PSK rotation ack, etc) proves the node is reachable
// and accepting our admin packets -- weaker evidence than a full
// GetConfig readback, but enough to displace the "stale" pill the
// frontend would otherwise show on a node that just rotated.
//
// admin_key_fps + is_managed are deliberately left untouched: they
// reflect what we last actually read from the node, and a SetChannel ack
// doesn't tell us anything new about them.
func (s *Store) MarkTrustVerifiedNow(ctx context.Context, nodeNum uint32, method VerifyMethod) error {
	_, err := s.db.Pool.Exec(ctx, `
		UPDATE fleet_node_trust
		   SET last_verified_at = now(),
		       last_verify_method = $2,
		       last_drift_check_at = now()
		 WHERE node_num = $1`, nodeNum, string(method))
	if err != nil {
		return fmt.Errorf("mark trust verified: %w", err)
	}
	return nil
}

// UpdateTargetPhase rewrites a single target's phase + lastError inside
// fleet_rotations.targets. Reads the current JSONB, finds the matching
// node entry, mutates it, writes back. Smaller wire footprint than a full
// UpdateRotationTargets when the worker just transitions one target.
//
// Sets the legacy `status` field in the JSONB to match (statusForPhase) so
// older frontend clients keep rendering correctly.
func (s *Store) UpdateTargetPhase(ctx context.Context, rotID string, nodeNum uint32, phase RotationPhase, errMsg string) error {
	rec, err := s.GetRotation(ctx, rotID)
	if err != nil {
		return err
	}
	found := false
	for i := range rec.Targets {
		if rec.Targets[i].NodeNum != nodeNum {
			continue
		}
		rec.Targets[i].Phase = phase
		rec.Targets[i].Status = statusForPhase(phase)
		rec.Targets[i].LastError = errMsg
		found = true
		break
	}
	if !found {
		return fmt.Errorf("target node_num %d not in rotation %s", nodeNum, rotID)
	}
	return s.UpdateRotationTargets(ctx, rotID, rec.Targets, nil)
}

// IncrementTargetAttempts adds 1 to attempts on a target. Used when entering
// an in-flight phase (PhasePushingB, PhasePromotingC) so the UI can show
// retry counts without conflating phase transitions and attempt counts.
func (s *Store) IncrementTargetAttempts(ctx context.Context, rotID string, nodeNum uint32) error {
	rec, err := s.GetRotation(ctx, rotID)
	if err != nil {
		return err
	}
	for i := range rec.Targets {
		if rec.Targets[i].NodeNum == nodeNum {
			rec.Targets[i].Attempts++
			return s.UpdateRotationTargets(ctx, rotID, rec.Targets, nil)
		}
	}
	return fmt.Errorf("target node_num %d not in rotation %s", nodeNum, rotID)
}

// UpsertPiLocalPhase records the Pi-Heltec's lifecycle position in this
// rotation. The check constraint on fleet_rotations.pi_local_phase rejects
// any value outside the {pending, staging_added, phase_d_promoted, retired}
// set, so a typo-fix-it-in-prod scenario is impossible.
func (s *Store) UpsertPiLocalPhase(ctx context.Context, rotID string, phase PiLocalPhase) error {
	_, err := s.db.Pool.Exec(ctx,
		`UPDATE fleet_rotations SET pi_local_phase = $2 WHERE id = $1`,
		rotID, string(phase))
	if err != nil {
		return fmt.Errorf("upsert pi_local_phase: %w", err)
	}
	return nil
}

// SetStagingChannelIndex pins which slot the staged-rotation worker chose
// for the new PSK during this rotation. RetryRotation reads it back so it
// knows where the existing staging definition lives on the remotes.
func (s *Store) SetStagingChannelIndex(ctx context.Context, rotID string, idx int32) error {
	_, err := s.db.Pool.Exec(ctx,
		`UPDATE fleet_rotations SET staging_channel_index = $2 WHERE id = $1`,
		rotID, idx)
	if err != nil {
		return fmt.Errorf("set staging_channel_index: %w", err)
	}
	return nil
}

// MarkRotationRetired stamps fleet_rotations.retired_at and flips
// pi_local_phase to retired. Only called by the operator-paced retirement
// flow after every fleet member is confirmed on the new PSK.
func (s *Store) MarkRotationRetired(ctx context.Context, rotID string) error {
	_, err := s.db.Pool.Exec(ctx,
		`UPDATE fleet_rotations
		    SET retired_at = now(),
		        pi_local_phase = 'retired'
		  WHERE id = $1`,
		rotID)
	if err != nil {
		return fmt.Errorf("mark rotation retired: %w", err)
	}
	return nil
}

// SetNodeCurrentPSKFP records the PSK fingerprint a node was last
// confirmed on (= Pi-Heltec's PRIMARY fp at the time of a successful
// GetTrust round-trip). Called from GetTrust on success.
//
// The retirement gate ANDs this across every managed-trust row: every
// member must equal the Pi's current PRIMARY fp. nil/empty means "never
// successfully verified since this column was added" -- treated as not-
// yet-migrated by the gate (operator must run a fresh Verify first).
func (s *Store) SetNodeCurrentPSKFP(ctx context.Context, nodeNum uint32, fp string) error {
	if fp == "" {
		return nil
	}
	_, err := s.db.Pool.Exec(ctx,
		`UPDATE fleet_node_trust SET current_psk_fp = $2 WHERE node_num = $1`,
		nodeNum, fp)
	if err != nil {
		return fmt.Errorf("set node current_psk_fp: %w", err)
	}
	return nil
}

// AllManagedNodesOnPSK reports whether every fleet_node_trust row whose
// node has at least one admin_key fingerprint set (== "managed by us")
// has current_psk_fp matching the supplied fp. Used as the gate for the
// retirement endpoint; returns the list of laggards on failure so the
// operator UI can surface "still pending: HB55, HB99" before the retire
// button enables.
func (s *Store) AllManagedNodesOnPSK(ctx context.Context, fp string) (allMigrated bool, laggards []uint32, err error) {
	rows, qErr := s.db.Pool.Query(ctx, `
		SELECT node_num
		  FROM fleet_node_trust
		 WHERE jsonb_array_length(admin_key_fps) > 0
		   AND (current_psk_fp IS NULL OR current_psk_fp <> $1)`, fp)
	if qErr != nil {
		return false, nil, fmt.Errorf("scan laggards: %w", qErr)
	}
	defer rows.Close()
	for rows.Next() {
		var n uint32
		if err := rows.Scan(&n); err != nil {
			return false, nil, fmt.Errorf("scan laggard: %w", err)
		}
		laggards = append(laggards, n)
	}
	return len(laggards) == 0, laggards, nil
}

// ClearRotationPSK NULLs fleet_rotations.new_psk. Called by the rotation
// runner once every target reaches acked, so a fully-successful rotation
// doesn't leave the raw PSK at rest in the DB longer than necessary.
// Failed-target rotations keep the PSK so RetryRotation works.
func (s *Store) ClearRotationPSK(ctx context.Context, id string) error {
	_, err := s.db.Pool.Exec(ctx,
		`UPDATE fleet_rotations SET new_psk = NULL WHERE id = $1`, id)
	if err != nil {
		return fmt.Errorf("clear rotation psk: %w", err)
	}
	return nil
}

// UpdateRotationTargets replaces the targets JSONB. Set completedAt non-nil
// when the rotation is fully resolved (every target is acked or failed and
// no retries remain pending). Pass nil during in-progress updates -- the
// COALESCE preserves the existing completed_at column value.
//
// Use a typed *time.Time rather than *interface{}: pgx cannot encode a
// pointer-to-interface (it can't infer the wire type from the dereferenced
// interface{} value) and falls over with "cannot find encode plan for
// timestamptz".
func (s *Store) UpdateRotationTargets(ctx context.Context, id string, targets []RotationTarget, completedAt *time.Time) error {
	targetsJSON, err := json.Marshal(targets)
	if err != nil {
		return fmt.Errorf("encode targets: %w", err)
	}
	_, err = s.db.Pool.Exec(ctx, `
		UPDATE fleet_rotations
		   SET targets = $2,
		       completed_at = COALESCE($3::timestamptz, completed_at)
		 WHERE id = $1`,
		id, targetsJSON, completedAt)
	if err != nil {
		return fmt.Errorf("update rotation targets: %w", err)
	}
	return nil
}

func (s *Store) GetRotation(ctx context.Context, id string) (*RotationRecord, error) {
	var r RotationRecord
	var targetsJSON []byte
	var ci, sci *int32
	var piPhase string
	err := s.db.Pool.QueryRow(ctx, `
		SELECT id::text, kind, channel_index, staging_channel_index,
		       COALESCE(started_by::text, ''),
		       started_at, completed_at, retired_at,
		       COALESCE(pi_local_phase, 'pending'),
		       targets,
		       COALESCE(new_psk_fp, ''), COALESCE(notes, '')
		  FROM fleet_rotations
		 WHERE id = $1`, id).
		Scan(&r.ID, &r.Kind, &ci, &sci, &r.StartedBy, &r.StartedAt, &r.CompletedAt,
			&r.RetiredAt, &piPhase, &targetsJSON, &r.NewPSKFP, &r.Notes)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("get rotation: %w", err)
	}
	r.ChannelIndex = ci
	r.StagingChannelIndex = sci
	r.PiLocalPhase = PiLocalPhase(piPhase)
	if err := json.Unmarshal(targetsJSON, &r.Targets); err != nil {
		return nil, fmt.Errorf("decode targets: %w", err)
	}
	// Back-fill Phase from legacy Status for rotations that pre-date the
	// 5-phase schema (000027). Lets the new worker / UI read old rows
	// uniformly without a separate code path.
	for i := range r.Targets {
		if r.Targets[i].Phase == "" {
			r.Targets[i].Phase = phaseForLegacyStatus(r.Targets[i].Status)
		}
	}
	return &r, nil
}

// phaseForLegacyStatus maps a pre-staging rotation's TargetStatus into the
// 5-phase enum so reads of historical rotations don't surface empty phase
// strings to the worker / UI.
func phaseForLegacyStatus(s TargetStatus) RotationPhase {
	switch s {
	case TargetStatusPending:
		return PhasePending
	case TargetStatusInFlight:
		return PhasePushingB
	case TargetStatusAcked:
		return PhaseOnNewPSK
	case TargetStatusFailed:
		return PhaseFailedB
	default:
		return PhasePending
	}
}

// --- Policy ---

func (s *Store) GetPolicy(ctx context.Context) (*FleetPolicy, error) {
	var p FleetPolicy
	var adminKeysJSON, channelsJSON []byte
	var updatedBy *string
	err := s.db.Pool.QueryRow(ctx, `
		SELECT expected_admin_key_fps, expected_is_managed,
		       expected_channels, updated_at, updated_by::text
		  FROM fleet_policy WHERE id = 1`).
		Scan(&adminKeysJSON, &p.ExpectedIsManaged, &channelsJSON,
			&p.UpdatedAt, &updatedBy)
	if err != nil {
		return nil, fmt.Errorf("get policy: %w", err)
	}
	if err := json.Unmarshal(adminKeysJSON, &p.ExpectedAdminKeyFPs); err != nil {
		return nil, fmt.Errorf("decode expected_admin_key_fps: %w", err)
	}
	if err := json.Unmarshal(channelsJSON, &p.ExpectedChannels); err != nil {
		return nil, fmt.Errorf("decode expected_channels: %w", err)
	}
	if updatedBy != nil {
		p.UpdatedBy = *updatedBy
	}
	return &p, nil
}

// UpdatePolicy replaces the singleton policy row in-place.
func (s *Store) UpdatePolicy(ctx context.Context, p FleetPolicy, updatedBy string) error {
	adminKeysJSON, err := json.Marshal(p.ExpectedAdminKeyFPs)
	if err != nil {
		return fmt.Errorf("encode expected_admin_key_fps: %w", err)
	}
	if p.ExpectedAdminKeyFPs == nil {
		adminKeysJSON = []byte(`[]`)
	}
	channelsJSON, err := json.Marshal(p.ExpectedChannels)
	if err != nil {
		return fmt.Errorf("encode expected_channels: %w", err)
	}
	if p.ExpectedChannels == nil {
		channelsJSON = []byte(`[]`)
	}
	_, err = s.db.Pool.Exec(ctx, `
		UPDATE fleet_policy
		   SET expected_admin_key_fps = $1,
		       expected_is_managed    = $2,
		       expected_channels      = $3,
		       updated_at             = NOW(),
		       updated_by             = NULLIF($4, '')::uuid
		 WHERE id = 1`,
		adminKeysJSON, p.ExpectedIsManaged, channelsJSON, updatedBy)
	if err != nil {
		return fmt.Errorf("update policy: %w", err)
	}
	return nil
}
