package fleetsec

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"

	"github.com/karamble/diginode-cc/internal/database"
)

// Store wraps the database queries for fleetsec rows. Mirrors the pattern
// used by audit.Service and other internal services -- thin layer on top
// of database.DB.Pool that hides the raw SQL from the service core.
type Store struct {
	db *database.DB
}

// NewStore constructs a Store over the provided database handle.
func NewStore(db *database.DB) *Store {
	return &Store{db: db}
}

// ErrNotFound is returned when a single-row lookup matches no rows.
var ErrNotFound = errors.New("fleetsec: not found")

// --- Identity registry ---

func (s *Store) ListIdentities(ctx context.Context) ([]IdentityRecord, error) {
	rows, err := s.db.Pool.Query(ctx, `
		SELECT id::text, label, public_key, fingerprint, role, source,
		       created_at, revoked_at, COALESCE(revoked_reason, ''),
		       COALESCE(notes, '')
		  FROM fleet_identities
		 ORDER BY (revoked_at IS NOT NULL), created_at DESC`)
	if err != nil {
		return nil, fmt.Errorf("list identities: %w", err)
	}
	defer rows.Close()

	var out []IdentityRecord
	for rows.Next() {
		var r IdentityRecord
		if err := rows.Scan(&r.ID, &r.Label, &r.PublicKey, &r.Fingerprint,
			&r.Role, &r.Source, &r.CreatedAt, &r.RevokedAt,
			&r.RevokedReason, &r.Notes); err != nil {
			return nil, fmt.Errorf("scan identity: %w", err)
		}
		out = append(out, r)
	}
	return out, rows.Err()
}

func (s *Store) GetIdentityByFingerprint(ctx context.Context, fp string) (*IdentityRecord, error) {
	var r IdentityRecord
	err := s.db.Pool.QueryRow(ctx, `
		SELECT id::text, label, public_key, fingerprint, role, source,
		       created_at, revoked_at, COALESCE(revoked_reason, ''),
		       COALESCE(notes, '')
		  FROM fleet_identities
		 WHERE fingerprint = $1`, fp).
		Scan(&r.ID, &r.Label, &r.PublicKey, &r.Fingerprint, &r.Role, &r.Source,
			&r.CreatedAt, &r.RevokedAt, &r.RevokedReason, &r.Notes)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("get identity by fingerprint: %w", err)
	}
	return &r, nil
}

// InsertIdentity creates a new entry. Caller is responsible for filling in
// Label, PublicKey, Fingerprint, Role, Source -- ID is generated by the DB.
func (s *Store) InsertIdentity(ctx context.Context, r IdentityRecord) (string, error) {
	var id string
	err := s.db.Pool.QueryRow(ctx, `
		INSERT INTO fleet_identities (label, public_key, fingerprint, role, source, notes)
		VALUES ($1, $2, $3, $4, $5, NULLIF($6, ''))
		RETURNING id::text`,
		r.Label, r.PublicKey, r.Fingerprint, r.Role, r.Source, r.Notes).
		Scan(&id)
	if err != nil {
		return "", fmt.Errorf("insert identity: %w", err)
	}
	return id, nil
}

// RevokeIdentity marks the identity revoked in-place. The pubkey row
// stays so that audit-log entries referencing this fingerprint remain
// resolvable to a label (just shows "<label> (revoked)" in UI).
func (s *Store) RevokeIdentity(ctx context.Context, fp, reason string) error {
	tag, err := s.db.Pool.Exec(ctx, `
		UPDATE fleet_identities
		   SET role = 'revoked',
		       revoked_at = NOW(),
		       revoked_reason = NULLIF($2, '')
		 WHERE fingerprint = $1`, fp, reason)
	if err != nil {
		return fmt.Errorf("revoke identity: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// --- Trust roster ---

// ListNodeTrust returns one row per known node, joined with the trust
// snapshot. Nodes without a trust row appear with default zero values
// and DriftStatus=unknown, so the UI naturally shows "unknown / not yet
// verified" for newly-discovered nodes.
func (s *Store) ListNodeTrust(ctx context.Context) ([]NodeTrustRecord, error) {
	rows, err := s.db.Pool.Query(ctx, `
		SELECT n.node_num,
		       COALESCE(n.node_id, ''),
		       COALESCE(n.long_name, ''),
		       COALESCE(n.short_name, ''),
		       COALESCE(n.sensor_short_id, ''),
		       n.last_heard,
		       COALESCE(n.is_online, false),
		       COALESCE(t.admin_key_fps, '[]'::jsonb),
		       COALESCE(t.is_managed, false),
		       t.last_verified_at,
		       COALESCE(t.last_verify_method, ''),
		       t.last_drift_check_at,
		       COALESCE(t.drift_status, 'unknown'),
		       COALESCE(t.notes, '')
		  FROM nodes n
		  LEFT JOIN fleet_node_trust t ON t.node_num = n.node_num
		 ORDER BY n.last_heard DESC NULLS LAST, n.node_num`)
	if err != nil {
		return nil, fmt.Errorf("list node trust: %w", err)
	}
	defer rows.Close()

	var out []NodeTrustRecord
	for rows.Next() {
		var r NodeTrustRecord
		var nodeNum int64
		var fpsJSON []byte
		if err := rows.Scan(&nodeNum, &r.NodeID, &r.LongName, &r.ShortName,
			&r.SensorShortID, &r.LastHeard, &r.IsOnline, &fpsJSON,
			&r.IsManaged, &r.LastVerifiedAt, &r.LastVerifyMethod,
			&r.LastDriftCheckAt, &r.DriftStatus, &r.Notes); err != nil {
			return nil, fmt.Errorf("scan node trust: %w", err)
		}
		r.NodeNum = uint32(nodeNum)
		if err := json.Unmarshal(fpsJSON, &r.AdminKeyFPs); err != nil {
			return nil, fmt.Errorf("decode admin_key_fps for node %d: %w", nodeNum, err)
		}
		out = append(out, r)
	}
	return out, rows.Err()
}

// GetNodeTrust returns a single row, joined the same way as ListNodeTrust.
// Returns ErrNotFound if the node doesn't exist in the nodes table.
func (s *Store) GetNodeTrust(ctx context.Context, nodeNum uint32) (*NodeTrustRecord, error) {
	var r NodeTrustRecord
	var nn int64
	var fpsJSON []byte
	err := s.db.Pool.QueryRow(ctx, `
		SELECT n.node_num,
		       COALESCE(n.node_id, ''),
		       COALESCE(n.long_name, ''),
		       COALESCE(n.short_name, ''),
		       COALESCE(n.sensor_short_id, ''),
		       n.last_heard,
		       COALESCE(n.is_online, false),
		       COALESCE(t.admin_key_fps, '[]'::jsonb),
		       COALESCE(t.is_managed, false),
		       t.last_verified_at,
		       COALESCE(t.last_verify_method, ''),
		       t.last_drift_check_at,
		       COALESCE(t.drift_status, 'unknown'),
		       COALESCE(t.notes, '')
		  FROM nodes n
		  LEFT JOIN fleet_node_trust t ON t.node_num = n.node_num
		 WHERE n.node_num = $1`, int64(nodeNum)).
		Scan(&nn, &r.NodeID, &r.LongName, &r.ShortName, &r.SensorShortID,
			&r.LastHeard, &r.IsOnline, &fpsJSON, &r.IsManaged,
			&r.LastVerifiedAt, &r.LastVerifyMethod, &r.LastDriftCheckAt,
			&r.DriftStatus, &r.Notes)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("get node trust: %w", err)
	}
	r.NodeNum = uint32(nn)
	if err := json.Unmarshal(fpsJSON, &r.AdminKeyFPs); err != nil {
		return nil, fmt.Errorf("decode admin_key_fps: %w", err)
	}
	return &r, nil
}

// UpsertNodeTrust writes the trust snapshot for a node, creating the row
// if it doesn't exist. Used after a successful get_config(SECURITY) reply.
func (s *Store) UpsertNodeTrust(ctx context.Context, r NodeTrustRecord) error {
	fpsJSON, err := json.Marshal(r.AdminKeyFPs)
	if err != nil {
		return fmt.Errorf("encode admin_key_fps: %w", err)
	}
	if r.AdminKeyFPs == nil {
		fpsJSON = []byte(`[]`)
	}
	_, err = s.db.Pool.Exec(ctx, `
		INSERT INTO fleet_node_trust (
			node_num, admin_key_fps, is_managed,
			last_verified_at, last_verify_method,
			last_drift_check_at, drift_status, notes
		) VALUES ($1, $2, $3, $4, NULLIF($5, ''), $6, $7, NULLIF($8, ''))
		ON CONFLICT (node_num) DO UPDATE SET
			admin_key_fps       = EXCLUDED.admin_key_fps,
			is_managed          = EXCLUDED.is_managed,
			last_verified_at    = COALESCE(EXCLUDED.last_verified_at, fleet_node_trust.last_verified_at),
			last_verify_method  = COALESCE(EXCLUDED.last_verify_method, fleet_node_trust.last_verify_method),
			last_drift_check_at = COALESCE(EXCLUDED.last_drift_check_at, fleet_node_trust.last_drift_check_at),
			drift_status        = EXCLUDED.drift_status,
			notes               = COALESCE(EXCLUDED.notes, fleet_node_trust.notes)`,
		int64(r.NodeNum), fpsJSON, r.IsManaged,
		r.LastVerifiedAt, string(r.LastVerifyMethod),
		r.LastDriftCheckAt, string(r.DriftStatus), r.Notes)
	if err != nil {
		return fmt.Errorf("upsert node trust: %w", err)
	}
	return nil
}

// --- Channels ---

func (s *Store) ListChannels(ctx context.Context) ([]ChannelRecord, error) {
	rows, err := s.db.Pool.Query(ctx, `
		SELECT channel_index, name, role,
		       COALESCE(psk_fingerprint, ''), COALESCE(psk_length, 0),
		       last_rotated_at, COALESCE(last_rotated_by::text, ''),
		       COALESCE(last_rotation_id::text, '')
		  FROM fleet_channels
		 ORDER BY channel_index`)
	if err != nil {
		return nil, fmt.Errorf("list channels: %w", err)
	}
	defer rows.Close()

	var out []ChannelRecord
	for rows.Next() {
		var r ChannelRecord
		if err := rows.Scan(&r.Index, &r.Name, &r.Role, &r.PSKFingerprint,
			&r.PSKLength, &r.LastRotatedAt, &r.LastRotatedBy,
			&r.LastRotationID); err != nil {
			return nil, fmt.Errorf("scan channel: %w", err)
		}
		out = append(out, r)
	}
	return out, rows.Err()
}

// UpsertChannel writes a snapshot for one channel index.
func (s *Store) UpsertChannel(ctx context.Context, r ChannelRecord) error {
	_, err := s.db.Pool.Exec(ctx, `
		INSERT INTO fleet_channels (
			channel_index, name, role, psk_fingerprint, psk_length,
			last_rotated_at, last_rotated_by, last_rotation_id
		) VALUES ($1, $2, $3, NULLIF($4, ''), NULLIF($5, 0)::int,
		          $6, NULLIF($7, '')::uuid, NULLIF($8, '')::uuid)
		ON CONFLICT (channel_index) DO UPDATE SET
			name             = EXCLUDED.name,
			role             = EXCLUDED.role,
			psk_fingerprint  = COALESCE(EXCLUDED.psk_fingerprint, fleet_channels.psk_fingerprint),
			psk_length       = COALESCE(EXCLUDED.psk_length, fleet_channels.psk_length),
			last_rotated_at  = COALESCE(EXCLUDED.last_rotated_at, fleet_channels.last_rotated_at),
			last_rotated_by  = COALESCE(EXCLUDED.last_rotated_by, fleet_channels.last_rotated_by),
			last_rotation_id = COALESCE(EXCLUDED.last_rotation_id, fleet_channels.last_rotation_id)`,
		r.Index, r.Name, string(r.Role), r.PSKFingerprint, r.PSKLength,
		r.LastRotatedAt, r.LastRotatedBy, r.LastRotationID)
	if err != nil {
		return fmt.Errorf("upsert channel: %w", err)
	}
	return nil
}

// --- Rotations ---

// InsertRotation creates a new rotation row and returns its UUID. Targets
// are typically all in 'pending' status at insert time; UpdateRotation
// transitions them as the orchestrator processes them.
func (s *Store) InsertRotation(ctx context.Context, r RotationRecord) (string, error) {
	targets, err := json.Marshal(r.Targets)
	if err != nil {
		return "", fmt.Errorf("encode targets: %w", err)
	}
	var id string
	err = s.db.Pool.QueryRow(ctx, `
		INSERT INTO fleet_rotations (kind, channel_index, started_by, targets, new_psk_fp, notes)
		VALUES ($1, $2, NULLIF($3, '')::uuid, $4, NULLIF($5, ''), NULLIF($6, ''))
		RETURNING id::text`,
		string(r.Kind), r.ChannelIndex, r.StartedBy, targets, r.NewPSKFP, r.Notes).
		Scan(&id)
	if err != nil {
		return "", fmt.Errorf("insert rotation: %w", err)
	}
	return id, nil
}

// UpdateRotationTargets replaces the targets JSONB. Set completedAt non-nil
// when the rotation is fully resolved (every target is acked or failed and
// no retries remain pending).
func (s *Store) UpdateRotationTargets(ctx context.Context, id string, targets []RotationTarget, completedAt *interface{}) error {
	targetsJSON, err := json.Marshal(targets)
	if err != nil {
		return fmt.Errorf("encode targets: %w", err)
	}
	_, err = s.db.Pool.Exec(ctx, `
		UPDATE fleet_rotations
		   SET targets = $2,
		       completed_at = COALESCE($3::timestamptz, completed_at)
		 WHERE id = $1`,
		id, targetsJSON, completedAt)
	if err != nil {
		return fmt.Errorf("update rotation targets: %w", err)
	}
	return nil
}

func (s *Store) GetRotation(ctx context.Context, id string) (*RotationRecord, error) {
	var r RotationRecord
	var targetsJSON []byte
	var ci *int32
	err := s.db.Pool.QueryRow(ctx, `
		SELECT id::text, kind, channel_index,
		       COALESCE(started_by::text, ''),
		       started_at, completed_at, targets,
		       COALESCE(new_psk_fp, ''), COALESCE(notes, '')
		  FROM fleet_rotations
		 WHERE id = $1`, id).
		Scan(&r.ID, &r.Kind, &ci, &r.StartedBy, &r.StartedAt, &r.CompletedAt,
			&targetsJSON, &r.NewPSKFP, &r.Notes)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("get rotation: %w", err)
	}
	r.ChannelIndex = ci
	if err := json.Unmarshal(targetsJSON, &r.Targets); err != nil {
		return nil, fmt.Errorf("decode targets: %w", err)
	}
	return &r, nil
}

// --- Policy ---

func (s *Store) GetPolicy(ctx context.Context) (*FleetPolicy, error) {
	var p FleetPolicy
	var adminKeysJSON, channelsJSON []byte
	var updatedBy *string
	err := s.db.Pool.QueryRow(ctx, `
		SELECT expected_admin_key_fps, expected_is_managed,
		       expected_channels, updated_at, updated_by::text
		  FROM fleet_policy WHERE id = 1`).
		Scan(&adminKeysJSON, &p.ExpectedIsManaged, &channelsJSON,
			&p.UpdatedAt, &updatedBy)
	if err != nil {
		return nil, fmt.Errorf("get policy: %w", err)
	}
	if err := json.Unmarshal(adminKeysJSON, &p.ExpectedAdminKeyFPs); err != nil {
		return nil, fmt.Errorf("decode expected_admin_key_fps: %w", err)
	}
	if err := json.Unmarshal(channelsJSON, &p.ExpectedChannels); err != nil {
		return nil, fmt.Errorf("decode expected_channels: %w", err)
	}
	if updatedBy != nil {
		p.UpdatedBy = *updatedBy
	}
	return &p, nil
}

// UpdatePolicy replaces the singleton policy row in-place.
func (s *Store) UpdatePolicy(ctx context.Context, p FleetPolicy, updatedBy string) error {
	adminKeysJSON, err := json.Marshal(p.ExpectedAdminKeyFPs)
	if err != nil {
		return fmt.Errorf("encode expected_admin_key_fps: %w", err)
	}
	if p.ExpectedAdminKeyFPs == nil {
		adminKeysJSON = []byte(`[]`)
	}
	channelsJSON, err := json.Marshal(p.ExpectedChannels)
	if err != nil {
		return fmt.Errorf("encode expected_channels: %w", err)
	}
	if p.ExpectedChannels == nil {
		channelsJSON = []byte(`[]`)
	}
	_, err = s.db.Pool.Exec(ctx, `
		UPDATE fleet_policy
		   SET expected_admin_key_fps = $1,
		       expected_is_managed    = $2,
		       expected_channels      = $3,
		       updated_at             = NOW(),
		       updated_by             = NULLIF($4, '')::uuid
		 WHERE id = 1`,
		adminKeysJSON, p.ExpectedIsManaged, channelsJSON, updatedBy)
	if err != nil {
		return fmt.Errorf("update policy: %w", err)
	}
	return nil
}
