// Package fleetsec implements the Fleet Security feature: control-center
// identity management, per-node trust roster (admin_key + is_managed),
// channel PSK rotation, and the recovery wizard. See FLEET_SECURITY.md
// at the repo root for the full design and §3.3 for the public service
// surface this package exposes.
package fleetsec

import "time"

// IdentityRole is the registry tag attached to a public key. Drives UX
// semantics in the Fleet Security tab: 'rescue' identities show in the
// recovery wizard, 'operator' identities show in bulk admin-key edits,
// 'primary' marks the active control-center key, 'revoked' is filtered
// out of normal flows.
type IdentityRole string

const (
	IdentityRolePrimary  IdentityRole = "primary"
	IdentityRoleRescue   IdentityRole = "rescue"
	IdentityRoleOperator IdentityRole = "operator"
	IdentityRoleRevoked  IdentityRole = "revoked"
)

// IdentitySource records how an identity entered the registry. Useful
// when reviewing audit logs after an incident.
type IdentitySource string

const (
	IdentitySourceAutoGenerated IdentitySource = "auto-generated"
	IdentitySourceImported      IdentitySource = "imported"
	IdentitySourceRotated       IdentitySource = "rotated"
)

// IdentityRecord mirrors a row in fleet_identities. Public-key bytes are
// the raw 32-byte X25519 public key; fingerprint is the colon-separated
// hex of the first 8 bytes of SHA-256(public_key). Private keys are NEVER
// stored here -- they live in the Heltec NVS or operator cold storage.
type IdentityRecord struct {
	ID            string         `json:"id"`
	Label         string         `json:"label"`
	PublicKey     []byte         `json:"-"` // never serialized to JSON; use FingerprintHex
	Fingerprint   string         `json:"fingerprint"`
	Role          IdentityRole   `json:"role"`
	Source        IdentitySource `json:"source"`
	CreatedAt     time.Time      `json:"createdAt"`
	RevokedAt     *time.Time     `json:"revokedAt,omitempty"`
	RevokedReason string         `json:"revokedReason,omitempty"`
	Notes         string         `json:"notes,omitempty"`
}

// VerifyMethod records which path was used to read a node's security
// config. local-usb is what `make build && diginode-cc` uses when the
// Halberd is plugged into the same host; remote-pkc is the standard mesh
// path that goes through the control-center Heltec.
type VerifyMethod string

const (
	VerifyMethodLocalUSB  VerifyMethod = "local-usb"
	VerifyMethodRemotePKC VerifyMethod = "remote-pkc"
)

// DriftStatus is the trust-roster health-pill state per node.
type DriftStatus string

const (
	DriftStatusUnknown     DriftStatus = "unknown"
	DriftStatusInPolicy    DriftStatus = "in-policy"
	DriftStatusDrift       DriftStatus = "drift"
	DriftStatusUnreachable DriftStatus = "unreachable"
)

// NodeTrustRecord mirrors a row in fleet_node_trust, joined with the basic
// identifying fields from nodes (LongName / ShortName / SensorShortID) so
// the UI can render rows without a second round-trip.
type NodeTrustRecord struct {
	NodeNum           uint32       `json:"nodeNum"`
	NodeID            string       `json:"nodeId,omitempty"`     // "!hex" form from nodes.node_id
	LongName          string       `json:"longName,omitempty"`
	ShortName         string       `json:"shortName,omitempty"`
	SensorShortID     string       `json:"sensorShortId,omitempty"`
	LastHeard         *time.Time   `json:"lastHeard,omitempty"`
	IsOnline          bool         `json:"isOnline"`
	AdminKeyFPs       []string     `json:"adminKeyFingerprints"`
	IsManaged         bool         `json:"isManaged"`
	LastVerifiedAt    *time.Time   `json:"lastVerifiedAt,omitempty"`
	LastVerifyMethod  VerifyMethod `json:"lastVerifyMethod,omitempty"`
	LastDriftCheckAt  *time.Time   `json:"lastDriftCheckAt,omitempty"`
	DriftStatus       DriftStatus  `json:"driftStatus"`
	Notes             string       `json:"notes,omitempty"`
}

// ChannelRole names map to meshpb.Channel_Role enum values. Stored as
// text in fleet_channels.role for readability; the service translates.
type ChannelRole string

const (
	ChannelRoleDisabled  ChannelRole = "DISABLED"
	ChannelRolePrimary   ChannelRole = "PRIMARY"
	ChannelRoleSecondary ChannelRole = "SECONDARY"
)

// ChannelRecord mirrors a row in fleet_channels. PSK fingerprints, never
// the PSK itself.
type ChannelRecord struct {
	Index           int32       `json:"index"`
	Name            string      `json:"name"`
	Role            ChannelRole `json:"role"`
	PSKFingerprint  string      `json:"pskFingerprint,omitempty"`
	PSKLength       int         `json:"pskLength"`
	LastRotatedAt   *time.Time  `json:"lastRotatedAt,omitempty"`
	LastRotatedBy   string      `json:"lastRotatedBy,omitempty"`
	LastRotationID  string      `json:"lastRotationId,omitempty"`
}

// RotationKind categorises a fleet_rotations row.
type RotationKind string

const (
	RotationKindPSK        RotationKind = "psk"
	RotationKindIdentity   RotationKind = "identity"
	RotationKindAdminKeys  RotationKind = "admin-keys"
	RotationKindRecovery   RotationKind = "recovery"
)

// TargetStatus is the per-node status pill in a rotation's progress drawer.
type TargetStatus string

const (
	TargetStatusPending  TargetStatus = "pending"
	TargetStatusInFlight TargetStatus = "in-flight"
	TargetStatusAcked    TargetStatus = "acked"
	TargetStatusFailed   TargetStatus = "failed"
)

// RotationTarget is one entry in fleet_rotations.targets JSONB. Status
// transitions: pending → in-flight → acked|failed. Last_error is set on
// failed only; cleared on retry success.
type RotationTarget struct {
	NodeNum   uint32       `json:"nodeNum"`
	Status    TargetStatus `json:"status"`
	Attempts  int          `json:"attempts"`
	LastError string       `json:"lastError,omitempty"`
}

// RotationRecord mirrors a row in fleet_rotations.
type RotationRecord struct {
	ID            string           `json:"id"`
	Kind          RotationKind     `json:"kind"`
	ChannelIndex  *int32           `json:"channelIndex,omitempty"`
	StartedBy     string           `json:"startedBy,omitempty"`
	StartedAt     time.Time        `json:"startedAt"`
	CompletedAt   *time.Time       `json:"completedAt,omitempty"`
	Targets       []RotationTarget `json:"targets"`
	NewPSKFP      string           `json:"newPskFingerprint,omitempty"`
	Notes         string           `json:"notes,omitempty"`
}

// FleetPolicy mirrors the singleton row in fleet_policy. Display-only in
// permissive mode -- the trust roster shows drift against ExpectedAdminKeyFPs
// but doesn't auto-reconcile.
type FleetPolicy struct {
	ExpectedAdminKeyFPs []string                  `json:"expectedAdminKeyFingerprints"`
	ExpectedIsManaged   bool                      `json:"expectedIsManaged"`
	ExpectedChannels    []ExpectedChannel         `json:"expectedChannels"`
	UpdatedAt           time.Time                 `json:"updatedAt"`
	UpdatedBy           string                    `json:"updatedBy,omitempty"`
}

// ExpectedChannel is the policy-level description of a channel: just its
// index and name and role. PSK is rotated separately, not policy-managed.
type ExpectedChannel struct {
	Index int32       `json:"index"`
	Name  string      `json:"name"`
	Role  ChannelRole `json:"role"`
}
