// Package fleetsec implements the Fleet Security feature: control-center
// identity management, per-node trust roster (admin_key + is_managed),
// channel PSK rotation, and the recovery wizard. See FLEET_SECURITY.md
// at the repo root for the full design and §3.3 for the public service
// surface this package exposes.
package fleetsec

import "time"

// IdentityRole is the registry tag attached to a public key. Drives UX
// semantics in the Fleet Security tab: 'rescue' identities show in the
// recovery wizard, 'operator' identities show in bulk admin-key edits,
// 'primary' marks the active control-center key, 'revoked' is filtered
// out of normal flows.
type IdentityRole string

const (
	IdentityRolePrimary  IdentityRole = "primary"
	IdentityRoleRescue   IdentityRole = "rescue"
	IdentityRoleOperator IdentityRole = "operator"
	IdentityRoleRevoked  IdentityRole = "revoked"
)

// IdentitySource records how an identity entered the registry. Useful
// when reviewing audit logs after an incident.
type IdentitySource string

const (
	IdentitySourceAutoGenerated IdentitySource = "auto-generated"
	IdentitySourceImported      IdentitySource = "imported"
	IdentitySourceRotated       IdentitySource = "rotated"
)

// IdentityRecord mirrors a row in fleet_identities. Public-key bytes are
// the raw 32-byte X25519 public key; fingerprint is the colon-separated
// hex of the first 8 bytes of SHA-256(public_key). Private keys are NEVER
// stored here -- they live in the Heltec NVS or operator cold storage.
type IdentityRecord struct {
	ID            string         `json:"id"`
	Label         string         `json:"label"`
	PublicKey     []byte         `json:"-"` // never serialized to JSON; use FingerprintHex
	Fingerprint   string         `json:"fingerprint"`
	Role          IdentityRole   `json:"role"`
	Source        IdentitySource `json:"source"`
	CreatedAt     time.Time      `json:"createdAt"`
	RevokedAt     *time.Time     `json:"revokedAt,omitempty"`
	RevokedReason string         `json:"revokedReason,omitempty"`
	Notes         string         `json:"notes,omitempty"`
}

// VerifyMethod records which path was used to read a node's security
// config. local-usb is what `make build && diginode-cc` uses when the
// Halberd is plugged into the same host; remote-pkc is the standard mesh
// path that goes through the control-center Heltec.
type VerifyMethod string

const (
	VerifyMethodLocalUSB  VerifyMethod = "local-usb"
	VerifyMethodRemotePKC VerifyMethod = "remote-pkc"
)

// DriftStatus is the trust-roster health-pill state per node.
type DriftStatus string

const (
	DriftStatusUnknown     DriftStatus = "unknown"
	DriftStatusInPolicy    DriftStatus = "in-policy"
	DriftStatusDrift       DriftStatus = "drift"
	DriftStatusUnreachable DriftStatus = "unreachable"
)

// NodeTrustRecord mirrors a row in fleet_node_trust, joined with the basic
// identifying fields from nodes (LongName / ShortName / SensorShortID) so
// the UI can render rows without a second round-trip.
type NodeTrustRecord struct {
	NodeNum           uint32       `json:"nodeNum"`
	NodeID            string       `json:"nodeId,omitempty"`     // "!hex" form from nodes.node_id
	LongName          string       `json:"longName,omitempty"`
	ShortName         string       `json:"shortName,omitempty"`
	SensorShortID     string       `json:"sensorShortId,omitempty"`
	LastHeard         *time.Time   `json:"lastHeard,omitempty"`
	IsOnline          bool         `json:"isOnline"`
	AdminKeyFPs       []string     `json:"adminKeyFingerprints"`
	IsManaged         bool         `json:"isManaged"`
	LastVerifiedAt    *time.Time   `json:"lastVerifiedAt,omitempty"`
	LastVerifyMethod  VerifyMethod `json:"lastVerifyMethod,omitempty"`
	LastDriftCheckAt  *time.Time   `json:"lastDriftCheckAt,omitempty"`
	DriftStatus       DriftStatus  `json:"driftStatus"`
	// CurrentPSKFP is the PSK fingerprint this node was last confirmed
	// on -- stamped during a successful Verify (PKC GetConfig SECURITY
	// round-trip proves channel-layer alignment). Migration 000028
	// added the column. NULL means "never verified post-000028";
	// retirement gate treats null as not-yet-migrated.
	CurrentPSKFP      string       `json:"currentPskFp,omitempty"`
	// PreviousPSKFP records the PSK fingerprint this node was on
	// immediately before the most recent fleet-wide rotation that
	// stranded it. Pairs with a row in fleet_recovery_psks (same fp)
	// holding the actual PSK bytes the recover_stranded job needs.
	// Migration 000030.
	PreviousPSKFP     string       `json:"previousPskFp,omitempty"`
	StrandedSince     *time.Time   `json:"strandedSince,omitempty"`
	RecoveryAttempts  int          `json:"recoveryAttempts,omitempty"`
	LastRecoveryAt    *time.Time   `json:"lastRecoveryAt,omitempty"`
	LastRecoveryError string       `json:"lastRecoveryError,omitempty"`
	Notes             string       `json:"notes,omitempty"`
}

// RecoveryPSKRecord mirrors a row in fleet_recovery_psks. Holds the
// raw PSK bytes for one historical PSK that's still alive on Pi-Heltec
// as a SECONDARY recovery channel (slots 2..7). The dispatcher hook +
// recover_stranded job handler use this to re-rotate stranded nodes
// onto the current PSK without operator intervention. Migration 000031.
type RecoveryPSKRecord struct {
	Slot       int32      `json:"slot"`
	FP         string     `json:"fp"`
	PSK        []byte     `json:"-"` // never serialised over the API
	PSKHash    int16      `json:"pskHash"`
	AddedAt    time.Time  `json:"addedAt"`
	RotationID *string    `json:"rotationId,omitempty"`
}

// ChannelRole names map to meshpb.Channel_Role enum values. Stored as
// text in fleet_channels.role for readability; the service translates.
type ChannelRole string

const (
	ChannelRoleDisabled  ChannelRole = "DISABLED"
	ChannelRolePrimary   ChannelRole = "PRIMARY"
	ChannelRoleSecondary ChannelRole = "SECONDARY"
)

// ChannelRecord mirrors a row in fleet_channels. PSK fingerprints, never
// the PSK itself.
type ChannelRecord struct {
	Index           int32       `json:"index"`
	Name            string      `json:"name"`
	Role            ChannelRole `json:"role"`
	PSKFingerprint  string      `json:"pskFingerprint,omitempty"`
	PSKLength       int         `json:"pskLength"`
	LastRotatedAt   *time.Time  `json:"lastRotatedAt,omitempty"`
	LastRotatedBy   string      `json:"lastRotatedBy,omitempty"`
	LastRotationID  string      `json:"lastRotationId,omitempty"`
}

// RotationKind categorises a fleet_rotations row.
type RotationKind string

const (
	RotationKindPSK        RotationKind = "psk"
	RotationKindIdentity   RotationKind = "identity"
	RotationKindAdminKeys  RotationKind = "admin-keys"
	RotationKindRecovery   RotationKind = "recovery"
)

// TargetStatus is the per-node status pill in a rotation's progress drawer.
// Retained for back-compat with frontend clients that read the legacy
// `status` field; new code uses RotationPhase via RotationTarget.Phase.
// statusForPhase() derives the right legacy status from a phase value.
type TargetStatus string

const (
	TargetStatusPending  TargetStatus = "pending"
	TargetStatusInFlight TargetStatus = "in-flight"
	TargetStatusAcked    TargetStatus = "acked"
	TargetStatusFailed   TargetStatus = "failed"
)

// RotationPhase is the per-target phase for a staged 5-phase PSK rotation
// (project_psk_rotation_secondary_channel_staging.md).
//
// Phase B = Pi pushes new PSK to the remote on a SECONDARY channel slot.
// Phase C = remote promotes the SECONDARY to PRIMARY.
//
// failed_b: Phase B push failed; remote stays on PSK_OLD only and is
// fully reachable -- safe to retry from PhasePending.
// failed_c: Phase B succeeded but Phase C didn't; remote has the new PSK
// on a SECONDARY slot but never promoted -- still reachable on either
// channel; safe to retry from PhaseHasNewPSK.
type RotationPhase string

const (
	PhasePending      RotationPhase = "pending"
	PhasePushingB     RotationPhase = "phase_b_pushing"
	PhaseHasNewPSK    RotationPhase = "has_new_psk"
	PhasePromotingC   RotationPhase = "phase_c_promoting"
	PhaseOnNewPSK     RotationPhase = "on_new_psk"
	PhaseRetired      RotationPhase = "retired"
	PhaseFailedB      RotationPhase = "failed_b"
	PhaseFailedC      RotationPhase = "failed_c"
)

// statusForPhase maps the new phase enum back to the legacy 4-value status
// for backward-compatible clients (UI versions that haven't been updated to
// render the 5-phase stepper). The mapping collapses both failure modes to
// "failed" and both terminal-success states (on_new_psk, retired) to
// "acked".
func statusForPhase(p RotationPhase) TargetStatus {
	switch p {
	case PhasePending:
		return TargetStatusPending
	case PhaseOnNewPSK, PhaseRetired:
		return TargetStatusAcked
	case PhaseFailedB, PhaseFailedC:
		return TargetStatusFailed
	default:
		return TargetStatusInFlight
	}
}

// PiLocalPhase tracks the Pi-Heltec's place in a staged rotation. Persisted
// on fleet_rotations.pi_local_phase.
//
//	pending           -- worker hasn't started or hasn't yet added staging
//	staging_added     -- Phase A done; Pi has the new PSK on a SECONDARY slot
//	phase_d_promoted  -- Phase D done; Pi PRIMARY = new PSK; old PSK kept as SECONDARY
//	retired           -- Phase E done; old slot DISABLED
type PiLocalPhase string

const (
	PiPhasePending         PiLocalPhase = "pending"
	PiPhaseStagingAdded    PiLocalPhase = "staging_added"
	PiPhasePhaseDPromoted  PiLocalPhase = "phase_d_promoted"
	PiPhaseRetired         PiLocalPhase = "retired"
)

// RotationTarget is one entry in fleet_rotations.targets JSONB. Phase is
// the new per-target lifecycle marker; Status is the legacy mirror kept in
// sync via statusForPhase() for back-compat with older clients.
type RotationTarget struct {
	NodeNum   uint32        `json:"nodeNum"`
	Phase     RotationPhase `json:"phase,omitempty"`
	Status    TargetStatus  `json:"status"`
	Attempts  int           `json:"attempts"`
	LastError string        `json:"lastError,omitempty"`
}

// RotationRecord mirrors a row in fleet_rotations.
type RotationRecord struct {
	ID                   string           `json:"id"`
	Kind                 RotationKind     `json:"kind"`
	ChannelIndex         *int32           `json:"channelIndex,omitempty"`
	StagingChannelIndex  *int32           `json:"stagingChannelIndex,omitempty"`
	PiLocalPhase         PiLocalPhase     `json:"piLocalPhase,omitempty"`
	StartedBy            string           `json:"startedBy,omitempty"`
	StartedAt            time.Time        `json:"startedAt"`
	CompletedAt          *time.Time       `json:"completedAt,omitempty"`
	RetiredAt            *time.Time       `json:"retiredAt,omitempty"`
	Targets              []RotationTarget `json:"targets"`
	NewPSKFP             string           `json:"newPskFingerprint,omitempty"`
	Notes                string           `json:"notes,omitempty"`
}

// FleetPolicy mirrors the singleton row in fleet_policy. Display-only in
// permissive mode -- the trust roster shows drift against ExpectedAdminKeyFPs
// but doesn't auto-reconcile.
type FleetPolicy struct {
	ExpectedAdminKeyFPs []string                  `json:"expectedAdminKeyFingerprints"`
	ExpectedIsManaged   bool                      `json:"expectedIsManaged"`
	ExpectedChannels    []ExpectedChannel         `json:"expectedChannels"`
	UpdatedAt           time.Time                 `json:"updatedAt"`
	UpdatedBy           string                    `json:"updatedBy,omitempty"`
}

// ExpectedChannel is the policy-level description of a channel: just its
// index and name and role. PSK is rotated separately, not policy-managed.
type ExpectedChannel struct {
	Index int32       `json:"index"`
	Name  string      `json:"name"`
	Role  ChannelRole `json:"role"`
}
