package serial

import (
	"bytes"
	"testing"

	pb "github.com/karamble/diginode-cc/internal/meshpb"
	"google.golang.org/protobuf/proto"
)

// makeSetChannelAdmin returns an AdminMessage that pushes a Channel proto
// with a known PSK -- representative of what RotatePSK will build.
func makeSetChannelAdmin(idx int32, name string, psk []byte) *pb.AdminMessage {
	return &pb.AdminMessage{
		PayloadVariant: &pb.AdminMessage_SetChannel{
			SetChannel: &pb.Channel{
				Index: idx,
				Role:  pb.Channel_PRIMARY,
				Settings: &pb.ChannelSettings{
					Name: name,
					Psk:  psk,
				},
			},
		},
	}
}

// roundTrip encodes a ToRadio frame produced by one of our builders, then
// decodes it back through proto.Unmarshal and returns the inner pieces.
func roundTrip(t *testing.T, frame []byte) (*pb.MeshPacket, *pb.AdminMessage) {
	t.Helper()
	var tr pb.ToRadio
	if err := proto.Unmarshal(frame, &tr); err != nil {
		t.Fatalf("ToRadio unmarshal: %v", err)
	}
	pkt := tr.GetPacket()
	if pkt == nil {
		t.Fatal("ToRadio missing packet variant")
	}
	data := pkt.GetDecoded()
	if data == nil {
		t.Fatal("MeshPacket missing decoded variant")
	}
	if got := data.GetPortnum(); got != pb.PortNum_ADMIN_APP {
		t.Errorf("portnum = %v, want ADMIN_APP", got)
	}
	var admin pb.AdminMessage
	if err := proto.Unmarshal(data.GetPayload(), &admin); err != nil {
		t.Fatalf("AdminMessage unmarshal: %v", err)
	}
	return pkt, &admin
}

func TestBuildAdminPacket_RoundTrip(t *testing.T) {
	const localNode uint32 = 0xdeadbeef
	want := makeSetChannelAdmin(0, "halberd-data", bytes.Repeat([]byte{0xab}, 16))

	frame, id, err := BuildAdminPacket(localNode, want)
	if err != nil {
		t.Fatalf("BuildAdminPacket: %v", err)
	}
	if id == 0 {
		t.Fatal("packet id must be non-zero (firmware rejects id=0)")
	}

	pkt, got := roundTrip(t, frame)

	if pkt.GetTo() != localNode {
		t.Errorf("to = %x, want %x", pkt.GetTo(), localNode)
	}
	if pkt.GetId() != id {
		t.Errorf("packet.id = %x, want returned id %x", pkt.GetId(), id)
	}
	if !pkt.GetWantAck() {
		t.Error("want_ack should be true for admin packets")
	}
	if pkt.GetPkiEncrypted() {
		t.Error("local admin should not set pki_encrypted")
	}

	gotCh := got.GetSetChannel()
	if gotCh == nil {
		t.Fatal("AdminMessage variant != set_channel")
	}
	if gotCh.GetIndex() != 0 {
		t.Errorf("channel index = %d, want 0", gotCh.GetIndex())
	}
	if gotCh.GetSettings().GetName() != "halberd-data" {
		t.Errorf("channel name = %q", gotCh.GetSettings().GetName())
	}
	if !bytes.Equal(gotCh.GetSettings().GetPsk(), bytes.Repeat([]byte{0xab}, 16)) {
		t.Errorf("psk mismatch")
	}
}

func TestBuildAdminPacketPKC_RoundTrip(t *testing.T) {
	const remoteNode uint32 = 0xa1b2c3d4
	want := makeSetChannelAdmin(0, "halberd-data", bytes.Repeat([]byte{0xcd}, 32))

	frame, id, err := BuildAdminPacketPKC(remoteNode, want)
	if err != nil {
		t.Fatalf("BuildAdminPacketPKC: %v", err)
	}
	if id == 0 {
		t.Fatal("packet id must be non-zero")
	}

	pkt, got := roundTrip(t, frame)

	if pkt.GetTo() != remoteNode {
		t.Errorf("to = %x, want %x", pkt.GetTo(), remoteNode)
	}
	if !pkt.GetPkiEncrypted() {
		t.Error("PKC packet must have pki_encrypted=true")
	}
	if !pkt.GetWantAck() {
		t.Error("want_ack should be true for admin packets")
	}
	if got.GetSetChannel() == nil {
		t.Error("AdminMessage variant != set_channel")
	}
}

func TestBuildAdminPacketPKC_RejectsBroadcast(t *testing.T) {
	for _, dest := range []uint32{0, BroadcastAddr} {
		_, _, err := BuildAdminPacketPKC(dest, makeSetChannelAdmin(0, "x", nil))
		if err == nil {
			t.Errorf("dest=%x: expected error, got nil", dest)
		}
	}
}

func TestBuildAdminPacket_NilMessageRejected(t *testing.T) {
	if _, _, err := BuildAdminPacket(1, nil); err == nil {
		t.Error("BuildAdminPacket(nil) should error")
	}
	if _, _, err := BuildAdminPacketPKC(1, nil); err == nil {
		t.Error("BuildAdminPacketPKC(nil) should error")
	}
}

// Confirms the wire format actually carries the field numbers we cited in
// FLEET_SECURITY.md §3.1: AdminMessage.set_channel = 33, MeshPacket.pki_encrypted = 17.
// Decodes the raw bytes (not the high-level helpers) to verify the field tags
// generated by protoc match the table; if the upstream proto ever renumbers
// these, this test fails before any integration test does.
func TestBuildAdminPacket_FieldNumbersMatchPlan(t *testing.T) {
	frame, _, err := BuildAdminPacketPKC(0xa1b2c3d4, makeSetChannelAdmin(0, "x", nil))
	if err != nil {
		t.Fatalf("BuildAdminPacketPKC: %v", err)
	}
	var tr pb.ToRadio
	if err := proto.Unmarshal(frame, &tr); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	pkt := tr.GetPacket()
	// Use protoreflect to inspect actual field numbers used by this codepath.
	pktDesc := pkt.ProtoReflect().Descriptor()
	pkiField := pktDesc.Fields().ByName("pki_encrypted")
	if pkiField == nil {
		t.Fatal("MeshPacket has no pki_encrypted field")
	}
	if got := pkiField.Number(); got != 17 {
		t.Errorf("pki_encrypted field = %d, want 17 (per FLEET_SECURITY.md §3.1)", got)
	}

	adminDesc := (&pb.AdminMessage{}).ProtoReflect().Descriptor()
	setCh := adminDesc.Fields().ByName("set_channel")
	if setCh == nil {
		t.Fatal("AdminMessage has no set_channel field")
	}
	if got := setCh.Number(); got != 33 {
		t.Errorf("set_channel field = %d, want 33 (per FLEET_SECURITY.md §3.1)", got)
	}

	// Also check SecurityConfig.admin_key (field 3, repeated bytes).
	secDesc := (&pb.Config_SecurityConfig{}).ProtoReflect().Descriptor()
	adminKey := secDesc.Fields().ByName("admin_key")
	if adminKey == nil {
		t.Fatal("SecurityConfig has no admin_key field")
	}
	if got := adminKey.Number(); got != 3 {
		t.Errorf("admin_key field = %d, want 3", got)
	}
	if !adminKey.IsList() {
		t.Error("admin_key should be repeated")
	}
}
